### ISSUE TITLE
Not working correctly 

### ISSUE THREAD

**Issue by YHC2538** [JackMD/CPS#1]
If you're using win10, The plugin only counts right clicks, left clicks don't count at all

**Comment by Ifera** [comment]
This plugin was only designed to count clicks when you use a item or if you use an item on an entity. Thats the intended behavior.

https://github.com/JackMD/CPS/blob/e5fc6a9a992bc129a36bfa513e06d7c76cf939bf/src/JackMD/CPS/EventListener.php#L32
